apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: linux-containers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linux-containers
  template:
    metadata:
      labels:
        app: linux-containers
    spec:
      containers:
        - name: linux-container
          image: university/linuxcontainer:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: linux-containers
  labels:
    app: linux-containers
spec:
  type: LoadBalancer
  ports:
   - port: 8080
  selector:
    app: linux-containers
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: linux-containers-ingress
#   annotations:
#     ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#   - host: localhost
#     http:
#       paths:
#         - path: /persons
#           backend:
#             serviceName: linux-containers
#             servicePort: 8080
